### ISSUE TITLE
Thank you for starting the project. 

### ISSUE THREAD

**Issue by DjebbZ** [wolfgang/org#13]
I've just started to use Atom and I'm starting to realize that it could really be a modern Emacs. So I searched for a port of org-mode and found your project. 

Please don't abandon it ! I'm very interesting in the project. Thanks again.

**Comment by fullofcaffeine** [comment]
+1

**Comment by ezjones** [comment]
+1 
and add narrow and widen please

**Comment by spidey1** [comment]
+1
